### ISSUE TITLE
[Bug Report] Using @vue/test-utils in sync mode leads to test failures

### ISSUE THREAD

**Issue by kierans** [vuetifyjs/vue-cli-plugins#159] opened 2020-02-12 08:09 UTC
### Environment

**Vuetify Version:** 2.2.12
**Vue Version:** 2.6.10

### Steps to reproduce

1. Create a new project via Vue CLI
2. Ensure that the version of `@vue/test-utils` < `1.0.0-beta.30`
3. Write a set of unit tests that exercise form validation

### Expected behaviour

`npm run test:unit` runs successfully.

### Actual behaviour

`npm run test:unit` tests will fail with `TypeError: Cannot read property '$scopedSlots' of undefined` error message.

**Comment by kierans** [comment] 2020-02-12 08:12
As outlined in https://github.com/vuejs/vue-test-utils/issues/1137 the reason is due to `@vue/tes-utils` running in `sync` mode which doesn't work well with how Vue updates the DOM in a batch.

When adding Vuetify to a project via the CLI, I suggest that any entry of `@vue/test-utils` be upgraded to >= `1.0.0-beta.30` so that sync mode is no longer present. This will have the consequence of forcing unit tests to await DOM updates.

**Comment by KaelWD** [comment] 2020-02-13 05:54
Duplicate of vuetifyjs/vuetify#9151

> I suggest that any entry of `@vue/test-utils` be upgraded to >= `1.0.0-beta.30`

This would break any existing tests, the upgrade should be done manually if needed.

**Comment by kierans** [comment] 2020-02-13 06:48
> This would break any existing tests, the upgrade should be done manually if needed.

But it is likely that tests (at least those using `mount`) will break anyway because `sync` mode doesn't work well with Vuetify.

The plugin could output a warning message, or ask the user if they want to upgrade `@vue/test-utils`.

**Closed** 2021-08-04 04:10 UTC
