### ISSUE TITLE
Can not install vuetify due to No webpack.config.js file when create vue.js project using webpack.

### ISSUE THREAD

**Issue by SamnnyWong** [vuetifyjs/vue-cli-plugins#207] opened 2020-09-17 10:40 UTC
vue version: "vue": "^2.5.2"
command to init the project: vue init webpack vue-app
environment: cordova with vue.js
In https://vuetifyjs.com/en/getting-started/quick-start/#existing-applications it mentioned: "Once installed, locate your webpack.config.js file and copy the snippet below into the rules array. "
There is no webpack.config.js is presented in the projecture structure. But there are webpack.base.conf.js, webpack.dev.conf.js and webpack.prod.conf.js under the "build" directory. should I copy the snippet into all of these 3 files?
If so the doc needs to be modified.

**Comment by KaelWD** [comment] 2020-12-03 08:33
Duplicate of #151

**Closed by KaelWD** 2020-12-03 08:33 UTC
