### ISSUE TITLE
Typescript template support

### ISSUE THREAD

**Issue by BeatScherrer** [vuetifyjs/vue-cli-plugins#250] opened 2021-03-08 10:08 UTC
When trying to add vuetify v3 alpha with the vue-cli-plugin the template App cannot be found since it is checkinf for a `App.ts.vue` extension but only a `App.js` extension can be found:

```
🚀  Invoking generator for vue-cli-plugin-vuetify...
 WARN  conflicting versions for project dependency "sass-loader":

- ^8.0.2 injected by generator "undefined"
- ^10.0.0 injected by generator "vue-cli-plugin-vuetify"

Using newer version (^10.0.0), but this may cause build errors.
 ERROR  Error: ENOENT: no such file or directory, stat '/home/beat/Documents/my-app/node_modules/vue-cli-plugin-vuetify/generator/templates/v3/src/App.ts.vue'
Error: ENOENT: no such file or directory, stat '/home/beat/Documents/my-app/node_modules/vue-cli-plugin-vuetify/generator/templates/v3/src/App.ts.vue'
    at Object.statSync (fs.js:1086:3)
    at isBinaryFileSync (/home/beat/.nvm/versions/node/v14.16.0/lib/node_modules/@vue/cli/node_modules/isbinaryfile/lib/index.js:50:25)
    at renderFile (/home/beat/.nvm/versions/node/v14.16.0/lib/node_modules/@vue/cli/lib/GeneratorAPI.js:478:7)
    at /home/beat/.nvm/versions/node/v14.16.0/lib/node_modules/@vue/cli/lib/GeneratorAPI.js:312:27
    at Generator.resolveFiles (/home/beat/.nvm/versions/node/v14.16.0/lib/node_modules/@vue/cli/lib/Generator.js:268:13)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Generator.generate (/home/beat/.nvm/versions/node/v14.16.0/lib/node_modules/@vue/cli/lib/Generator.js:175:5)
    at async runGenerator (/home/beat/.nvm/versions/node/v14.16.0/lib/node_modules/@vue/cli/lib/invoke.js:111:3)
    at async invoke (/home/beat/.nvm/versions/node/v14.16.0/lib/node_modules/@vue/cli/lib/invoke.js:92:3)
```

**Comment by ElijahKotyluk** [comment] 2021-03-09 15:57
Duplicate of #245

**Closed by ElijahKotyluk** 2021-03-09 15:57 UTC
Labels: duplicate
