### ISSUE TITLE
[Bug Report] Sass-loader 9.0.1 prependData option removed, use additionalData instead breaks build

### ISSUE THREAD

**Issue by avenmore** [vuetifyjs/vue-cli-plugins#189] opened 2020-07-07 07:34 UTC
### Environment
**Vuetify Version:** 2.3.3
**Vue Version:** 2.6.11
**Browsers:** Firefox 78.0
**OS:** Windows 10

### Steps to reproduce
Update sass-loader to 9.0.1 and "npm run build". Outputs a flood of errors about invalid option prependData.

### Expected Behavior
Project builds.

### Actual Behavior
Build fails.

### Reproduction Link
<a href="" target="_blank"></a>

### Other comments
This change is listed under breaking changes for [sass-loader 9.0.0](https://github.com/webpack-contrib/sass-loader/releases).

I was able to build by hacking the following files:

...\node_modules\vuetify-loader\dev\webpack.config.js

```
function sassLoaderOptions (indentedSyntax = false) {
  return {
    implementation: require('sass'),
    additionalData: `@import "~@/_variables.scss"` + (indentedSyntax ? '' : ';'), //!
    sassOptions: { indentedSyntax },
  }
}
```

...\node_modules\vue-cli-plugin-vuetify\util\helpers.js

```
  } else if (sassLoaderVersion < 9) {
    if (opt.prependData) data.unshift(opt.prependData)
    opt.prependData = data.join('\n')
  } else {
    if (opt.additionalData) data.unshift(opt.additionalData)
    opt.additionalData = data.join('\n')
  }
```

**Comment by DRoet** [comment] 2020-07-07 08:20
duplicate of https://github.com/vuetifyjs/vue-cli-plugins/pull/185

**Closed** 2020-07-07 08:24 UTC
