### ISSUE TITLE
[Bug Report] TypeError: Received an unexpected value [object Undefined]

### ISSUE THREAD

**Issue by onurusluca** [vuetifyjs/vue-cli-plugins#288] opened 2021-08-03 01:50 UTC
### Environment
 "vue-cli-plugin-vuetify": "~2.4.1",

Browsers: Chrome 92.0.4515.107
OS: Windows 64

### Steps to reproduce

1. Open a vue project
2. vue add vuetify
3. Successfully installed plugin: vue-cli-plugin-vuetify
4. Choose a preset -> Default (recommended)

- Invoking generator for vue-cli-plugin-vuetify...
- Successfully installed plugin: vue-cli-plugin-vuetify
- TypeError: Received an unexpected value [object Undefined]

### Expected Behavior
no error

### Actual Behavior

>  ERROR  TypeError: Received an unexpected value [object Undefined]
TypeError: Received an unexpected value [object Undefined]
    at fromAST (C:\Users\userName\AppData\Roaming\npm\node_modules\@vue\cli\node_modules\jscodeshift\src\core.js:70:9)    at core (C:\Users\userName\AppData\Roaming\npm\node_modules\@vue\cli\node_modules\jscodeshift\src\core.js:45:5)   
    at newCore (C:\Users\userName\AppData\Roaming\npm\node_modules\@vue\cli\node_modules\jscodeshift\src\core.js:142:12)
    at toPropertyHash (C:\Users\userName\AppData\Roaming\npm\node_modules\@vue\cli\lib\util\codemods\injectOptions.js:19:49)
    at Array.map (<anonymous>)
    at injectOptions (C:\Users\userName\AppData\Roaming\npm\node_modules\@vue\cli\lib\util\codemods\injectOptions.js:20:42)
    at runTransformation (C:\Users\userName\AppData\Roaming\npm\node_modules\@vue\cli\node_modules\vue-codemod\dist\src\runTransformation.js:60:17)
    at C:\Users\userName\AppData\Roaming\npm\node_modules\@vue\cli\lib\Generator.js:290:23
    at Array.forEach (<anonymous>)
    at Generator.resolveFiles (C:\Users\userName\AppData\Roaming\npm\node_modules\@vue\cli\lib\Generator.js:276:24) 

### Notes

I believe this has something to do with TypeScript but I can't find what.

**Comment by ElijahKotyluk** [comment] 2021-08-03 19:20
Duplicate of #169

**Closed** 2021-08-04 02:45 UTC
Labels: duplicate
