### ISSUE TITLE
i have this error 

### ISSUE THREAD

**Issue by MohammadKz03** [vuetifyjs/vue-cli-plugins#201] opened 2020-09-04 06:33 UTC
failed again. here's the console spew:
mcorn@DESKTOP-55SQIHT MINGW64 ~/Documents/GitHub/vue/vuex-orm-localforage-exemples-master (master)
$ vue add vuetify
WARN There are uncommited changes in the current repository, it's recommended to commit or stash them first.
? Still proceed? Yes

�📦 Installing vue-cli-plugin-vuetify...

yarn add v1.21.1
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@1.2.9: The platform "win32" is incompatible with this module.
info "fsevents@1.2.9" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Saved 1 new dependency.
info Direct dependencies
└─ vue-cli-plugin-vuetify@2.0.5
info All dependencies
└─ vue-cli-plugin-vuetify@2.0.5
Done in 9.99s.
✔ Successfully installed plugin: vue-cli-plugin-vuetify

? Choose a preset: Default (recommended)

�🚀 Invoking generator for vue-cli-plugin-vuetify...
ERROR Error: You cannot call "get" on a collection with no paths. Instead, check the "length" property first to verify at least 1 path exists.
Error: You cannot call "get" on a collection with no paths. Instead, check the "length" property first to verify at least 1 path exists.
at Collection.get (C:\Users\mcorn\AppData\Roaming\npm\node_modules@vue\cli\node_modules\jscodeshift\src\Collection.js:215:13)
at injectOptions (C:\Users\mcorn\AppData\Roaming\npm\node_modules@vue\cli\lib\util\codemods\injectOptions.js:15:6)
at newTransform (C:\Users\mcorn\AppData\Roaming\npm\node_modules@vue\cli\node_modules\vue-jscodeshift-adapter\src\jscodeshift-mode.js:9:14)
at runCodemod (C:\Users\mcorn\AppData\Roaming\npm\node_modules@vue\cli\lib\util\runCodemod.js:29:26)
at Object.keys.forEach.file (C:\Users\mcorn\AppData\Roaming\npm\node_modules@vue\cli\lib\Generator.js:283:23)
at Array.forEach ()
at Generator.resolveFiles (C:\Users\mcorn\AppData\Roaming\npm\node_modules@vue\cli\lib\Generator.js:269:24)
at process._tickCallback (internal/process/next_tick.js:68:7)

$

@mcorning
 
mcorning commented on Mar 4
here is the new line in package.json:
"vue-cli-plugin-vuetify": "^2.0.5",

@mcorning
 
mcorning commented on Mar 4
and here is the new content in yarn.lock:
"@babel/code-frame@^7.8.3":
version "7.8.3"
resolved "https://registry.yarnpkg.com/@babel/code-frame/-/code-frame-7.8.3.tgz#33e25903d7481181534e12ec0a25f16b6fcf419e"
integrity sha512-a9gxpmdXtZEInkCSHUJDLHZVBgb1QS0jhss4cPP93EW7s+uC5bikET2twEF3KV+7rDblJcmNvTR7VJejqd2C2g==
dependencies:
"@babel/highlight" "^7.8.3"

**Comment by jacekkarczmarczyk** [comment] 2020-09-04 08:25
Duplicate of https://github.com/vuetifyjs/vue-cli-plugins/issues/140

**Closed by jacekkarczmarczyk** 2020-09-04 08:25 UTC
