### ISSUE TITLE
Vuetify error on invoking generator

### ISSUE THREAD

**Issue by MRmlik12** [vuetifyjs/vue-cli-plugins#262] opened 2021-04-11 19:28 UTC
Hi!

I have a problem with installing vuetify 3 on my migrated vue project from vue 2 to vue 3. I tried reinstall npm packages but not still working.

```ERROR  Error: You cannot call "get" on a collection with no paths. Instead, check the "length" property first to verify at least 1 path exists.
Error: You cannot call "get" on a collection with no paths. Instead, check the "length" property first to verify at least 1 path exists.
    at Collection.get (/usr/local/lib/node_modules/@vue/cli/node_modules/jscodeshift/src/Collection.js:213:13)
    at injectOptions (/usr/local/lib/node_modules/@vue/cli/lib/util/codemods/injectOptions.js:15:6)
    at runTransformation (/usr/local/lib/node_modules/@vue/cli/node_modules/vue-codemod/dist/src/runTransformation.js:60:17)
    at Object.keys.forEach.file (/usr/local/lib/node_modules/@vue/cli/lib/Generator.js:290:23)
    at Array.forEach (<anonymous>)
    at Generator.resolveFiles (/usr/local/lib/node_modules/@vue/cli/lib/Generator.js:276:24)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by jacekkarczmarczyk** [comment] 2021-04-11 20:13
Duplicate of https://github.com/vuetifyjs/vue-cli-plugins/issues/140

**Comment by jacekkarczmarczyk** [comment] 2021-04-11 20:15
How did you install Vuetify 3? The error looks like you're trying to install Vuetify 2 with Vue 3

**Comment by MRmlik12** [comment] 2021-04-11 21:04
I selected advanced mode but I choosed Preview (Vuetify3 + Vite) another error has been shown 

``` ERROR  Error: ENOENT: no such file or directory, stat '/home/mrmlik12/Projects/wulkanowy-web/frontend/node_modules/vue-cli-plugin-vuetify/generator/templates/v3/src/App.ts.vue'
Error: ENOENT: no such file or directory, stat '/home/mrmlik12/Projects/wulkanowy-web/frontend/node_modules/vue-cli-plugin-vuetify/generator/templates/v3/src/App.ts.vue'
    at Object.statSync (fs.js:855:3)
    at isBinaryFileSync (/usr/local/lib/node_modules/@vue/cli/node_modules/isbinaryfile/lib/index.js:50:25)
    at renderFile (/usr/local/lib/node_modules/@vue/cli/lib/GeneratorAPI.js:478:7)
    at _injectFileMiddleware.files (/usr/local/lib/node_modules/@vue/cli/lib/GeneratorAPI.js:312:27)
    at Generator.resolveFiles (/usr/local/lib/node_modules/@vue/cli/lib/Generator.js:268:13)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by Minalien** [comment] 2021-04-12 01:51
I'm seeing the exact same error. It seems like the TypeScript files aren't copied over for the currently-available version of the plugin.

Taking a peek into my `node_modules` shows them missing:
![image](https://user-images.githubusercontent.com/303723/114330553-d1f41a00-9af6-11eb-837e-279faa31c48a.png)

**Comment by Minalien** [comment] 2021-04-12 02:28
@MRmlik12 Don't know if you need it but just in case you do and it helps, you can do this as a workaround until they fix the issue. I did it through CLI but afaik it should work fine if using the web UI as well.

1. Clone this repository (or download the ZIP through GitHub, I'm not your mother).
2. Run `vue add vuetify`
3. Proceed as normal until the step that asks you to select your preset. **Do not** select the V3 or Vite presets yet.
4. Copy the `v3` folder from the `packages/vue-cli-plugin-vuetify/generator/templates` folder in the cloned repository, and paste it into your project's `node_modules/vue-cli-plugin-vuetify/generator/templates/` (make sure you allow it to overwrite the existing folder). This will copy over all of the missing TypeScript files.
5. Select the appropriate pre-set in your Vue CLI or web UI, and continue as normal.

**Comment by MRmlik12** [comment] 2021-04-12 06:06
@Minalien thanks for this solution. It works!

**Comment by MRmlik12** [comment] 2021-04-12 06:13
oh vite prewiev doesn't work properly 

```Error: Cannot find module 'worker_threads'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/mrmlik12/Projects/wulkanowy-web/frontend/node_modules/vite/dist/node/chunks/dep-e0f09032.js:18:24)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
```

**Comment by MRmlik12** [comment] 2021-04-12 06:52
Oh, I found new problem running vue-cli-service 
```
Error: [VuetifyLoaderPlugin Error] No matching rule for vue-loader found.
Make sure there is at least one root-level rule that uses vue-loader and VuetifyLoaderPlugin is applied after VueLoaderPlugin.
    at VuetifyLoaderPlugin.apply (/home/mrmlik12/Projects/wulkanowy-web/frontend/node_modules/vuetify-loader/lib/plugin.js:15:13)
    at webpack (/home/mrmlik12/Projects/wulkanowy-web/frontend/node_modules/webpack/lib/webpack.js:51:13)
    at serve (/home/mrmlik12/Projects/wulkanowy-web/frontend/node_modules/@vue/cli-service/lib/commands/serve.js:163:22)
    at process._tickCallback (internal/process/next_tick.js:68:7)
    at Function.Module.runMain (internal/modules/cjs/loader.js:834:11)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)

```

**Comment by ElijahKotyluk** [comment] 2021-05-02 19:49
@MRmlik12 The TypeScript issue should be resolved in the latest release, the .ts files were not published until the most release.
Are you still having issues with vue-loader?

**Closed** 2021-05-21 18:27 UTC

**Comment by ThaDaVos** [comment] 2022-08-19 08:03
> @MRmlik12 The TypeScript issue should be resolved in the latest release, the .ts files were not published until the most release. Are you still having issues with vue-loader?

Sadly it is not solved... there are missing again

**Comment by ThaDaVos** [comment] 2022-08-19 08:09
Even missing in the repo itself:
https://github.com/vuetifyjs/vue-cli-plugins/tree/master/packages/vue-cli-plugin-vuetify/generator/templates/v3/src

For now I copied it from `default/src`
