### ISSUE TITLE
[Bug Report] sass-loader 9.x breaking changes break vue-cli-plugin-vuetify

### ISSUE THREAD

**Issue by davydnorris** [vuetifyjs/vue-cli-plugins#188] opened 2020-07-05 05:27 UTC
### Environment

**Browsers:** Firefox 78.0
**OS:** Windows 10

### Steps to reproduce
sass-loader 9.x changes syntax for appended data yet again and breaks vue-cli-vuetify-plugin at this line:

https://github.com/vuetifyjs/vue-cli-plugins/blob/a1175973d44a19fed13c4e043015ecda66275047/packages/vue-cli-plugin-vuetify/util/helpers.js#L55-L63

Replace the section above with the following code:

```
  if (sassLoaderVersion < 8) {
    if (opt.data) data.unshift(opt.data)

    opt.data = data.join('\n')
  } else if (sassLoaderVersion === 8) {
    if (opt.prependData) data.unshift(opt.prependData)

    opt.prependData = data.join('\n')
  } else {
    if (opt.additionalData) data.unshift(opt.additionalData)

    opt.additionalData = data.join('\n')      
  }
```

### Expected Behavior
plugin compiles code properly

### Actual Behavior
```
 error  in ./node_modules/vuetify/src/components/VExpansionPanel/VExpansionPanel.sass

Module build failed (from ../node_modules/sass-loader/dist/cjs.js):
ValidationError: Invalid options object. Sass Loader has been initialized using an options object that does not match the API schema.
 - options has an unknown property 'prependData'. These properties are valid:
   object { implementation?, sassOptions?, additionalData?, sourceMap?, webpackImporter? }
    at validate (C:\workspaces\ppp\node_modules\schema-utils\dist\validate.js:96:11)
    at Object.loader (C:\workspaces\ppp\node_modules\sass-loader\dist\index.js:30:28)
```

### Reproduction Link
<a href="" target="_blank"></a>

**Comment by KaelWD** [comment] 2020-07-05 06:36
Duplicate of #185

**Closed by KaelWD** 2020-07-05 06:36 UTC
