### ISSUE TITLE
I got the same error

### ISSUE THREAD

**Issue by engjames256** [vuetifyjs/vue-cli-plugins#198] opened 2020-08-27 06:13 UTC
WARN  There are uncommitted changes in the current repository, it's recommended to commit or stash them first.
? Still proceed? Yes

📦  Installing vue-cli-plugin-vuetify...

+ vue-cli-plugin-vuetify@2.0.7
added 7 packages from 9 contributors in 30.417s

55 packages are looking for funding
  run `npm fund` for details

✔  Successfully installed plugin: vue-cli-plugin-vuetify

? Choose a preset: Default (recommended)

🚀  Invoking generator for vue-cli-plugin-vuetify...
 ERROR  Error: You cannot call "get" on a collection with no paths. Instead, check the "length" property first to verify at least 1 path exists.
Error: You cannot call "get" on a collection with no paths. Instead, check the "length" property first to verify at least 1 path exists.
    at Collection.get (/usr/local/share/.config/yarn/global/node_modules/jscodeshift/src/Collection.js:213:13)
    at injectOptions (/usr/local/share/.config/yarn/global/node_modules/@vue/cli/lib/util/codemods/injectOptions.js:15:6)
    at runTransformation (/usr/local/share/.config/yarn/global/node_modules/vue-codemod/dist/src/run-transformation.js:61:17)
    at /usr/local/share/.config/yarn/global/node_modules/@vue/cli/lib/Generator.js:290:23
    at Array.forEach (<anonymous>)
    at Generator.resolveFiles (/usr/local/share/.config/yarn/global/node_modules/@vue/cli/lib/Generator.js:276:24)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Generator.generate (/usr/local/share/.config/yarn/global/node_modules/@vue/cli/lib/Generator.js:175:5)
    at async runGenerator (/usr/local/share/.config/yarn/global/node_modules/@vue/cli/lib/invoke.js:111:3)
    at async invoke (/usr/local/share/.config/yarn/global/node_modules/@vue/cli/lib/invoke.js:92:3)

**Comment by jacekkarczmarczyk** [comment] 2020-08-27 06:19
Most probably you've selected Vue 3 while creating a new project. if not please provide a reproduction or describe exact steps to reproduce your problem

Closing as duplicate of https://github.com/vuetifyjs/vue-cli-plugins/issues/140

**Closed by jacekkarczmarczyk** 2020-08-27 06:19 UTC
