### ISSUE TITLE
Specify variables location

### ISSUE THREAD

**Issue by hamishjohnson** [vuetifyjs/vue-cli-plugins#158] opened 2020-02-09 11:29 UTC
According to https://vuetifyjs.com/en/customization/sass-variables#vue-cli-install

In order to specify your variable overrides, you must put it in a styles/scss/sass folder in the src. I would like to be able to specify where these styles are stored.

**Comment by XavierChevalier** [comment] 2020-06-09 12:15
The change of path will be very useful!
To solve the problem temporarily, we had to create a `src/sass/variables.scss` file in which we have :
```scss
// ./src/sass/variables.scss

@import "./../assets/styles/settings/variables"; // Here, the true path to the stored file.
```
We are hoping for an option to avoid this.

**Comment by davydnorris** [comment] 2020-07-05 03:19
See #187 for an additional bug related to this

**Comment by johnleider** [comment] 2021-09-06 21:59
Duplicate of #187

**Closed by johnleider** 2021-09-06 21:59 UTC
